# this file is used for kitchen dokken
# especially for integration tests in the CI
---
driver:
  name: dokken
  privileged: true # because Docker and systemd
  chef_image: cincproject/cinc
  chef_version: <%= ENV['CINC_VERSION'] || 'latest' %>

provisioner:
  name: dokken
  product_name: cinc
  chef_binary: /opt/cinc/bin/cinc-client

transport:
  name: dokken

platforms:
- name: amazonlinux-1
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init
- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2
    pid_one_command: /usr/lib/systemd/systemd
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
- name: centos-stream-8
  driver:
    image: dokken/centos-stream-8
    pid_one_command: /usr/lib/systemd/systemd
- name: centos-stream-9
  driver:
    image: dokken/centos-stream-9
    pid_one_command: /usr/lib/systemd/systemd
- name: almalinux-8
  driver:
    image: dokken/almalinux-8
    pid_one_command: /usr/lib/systemd/systemd
- name: almalinux-9
  driver:
    image: dokken/almalinux-9
    pid_one_command: /usr/lib/systemd/systemd
- name: rockylinux-8
  driver:
    image: dokken/rockylinux-8
    pid_one_command: /usr/lib/systemd/systemd
- name: rockylinux-9
  driver:
    image: dokken/rockylinux-9
    pid_one_command: /usr/lib/systemd/systemd
- name: oracle-7
  driver:
    image: oraclelinux:7
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-10
  driver:
    image: dokken/debian-10
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: debian-11
  driver:
    image: dokken/debian-11
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: fedora-37
  driver:
    image: dokken/fedora-37
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum
- name: fedora-38
  driver:
    image: dokken/fedora-38
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum
- name: opensuse-42
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd
- name: ubuntu-18-04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
- name: ubuntu-20-04
  driver:
    image: dokken/ubuntu-20.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
