---
driver:
  name: vagrant

platforms:
- name: ubuntu-18-04
  driver_config:
    box: bento/ubuntu-18.04
- name: ubuntu-20-04
  driver_config:
    box: bento/ubuntu-20.04
- name: centos-7
- name: centos-stream-8
- name: centos-stream-9
- name: almalinux-8
- name: almalinux-9
- name: rockylinux-8
- name: rockylinux-9
- name: oracle-7
- name: debian-10
- name: debian-11
- name: fedora-37
- name: fedora-38
- name: opensuse-leap-42
- name: amazonlinux-1
  driver_config:
    box: realreadme/amazon2016.09
- name: amazonlinux-2
  driver_config:
    box: stakahashi/amazonlinux2

provisioner:
  name: chef_zero
  product_name: cinc
<% if ENV['CINC_VERSION'] %>
  product_version: '<%= ENV['CINC_VERSION'] %>'
<% end %>

verifier:
  name: inspec
  sudo: true

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
- name: modules_disabled
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - path: test/integration/default
    attributes:
      kernel_modules_disabled: 1
